---
- name: 配置用户和安装软件
  hosts: all
  become: true
  gather_facts: true

  vars:
    username: myuser
    user_password: "1234"

  roles:
    - role: init-server
      vars:
        user_name: "{{ username }}"
        user_password: "{{ user_password }}"
    - docker
